language: node_js
sudo: false
node_js:
  - "4"
  - "5"
cache:
  directories:
  - node_modules
env:
  global:
    - LOGS_DIR=/tmp/react-gpt-build/logs
matrix:
  fast_finish: true
  include:
    - node_js: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - mkdir -p $LOGS_DIR
script:
  - npm test
